### ISSUE TITLE
If i move to section settings, error apears.

### ISSUE THREAD

**Issue by GeoLMg** [omegaui/cliptopia#19]
# Bug Report Z-959

**Distro**: "Ubuntu 23.10"
**Version**: "23.10"
**Parent Distro**: debian

**Time**: Dec 22, 2023 16:07
**Area of Impact**: PROD Session
**Message**: [Zone Guard]
**Additional Description**: Error caught by Zone Guard.
**Error**: ProcessException: No such file or directory
  Command: java --help
```shell
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      doesCommandExists (package:cliptopia/core/utils.dart:354)
#5      _SettingsInitializedStateViewState._buildTroubleshootPage.buildTile (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:633)
#6      _SettingsInitializedStateViewState._buildTroubleshootPage (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:749)
#7      _SettingsInitializedStateViewState.build (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:159)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#18     _rootRun (dart:async/zone.dart:1399)
#19     _CustomZone.run (dart:async/zone.dart:1301)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#21     _invoke (dart:ui/hooks.dart:314)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382)
#23     _drawFrame (dart:ui/hooks.dart:283)
![image](https://github.com/omegaui/cliptopia/assets/65762308/e4e1605e-2b8f-421a-a465-71931f7f6d9c)

```

**Comment by GeoLMg** [comment]
I solve it by installing openjdk-17-jdk. I forgot to do it.
