### ISSUE TITLE
`flutter: Null check operator used on a null value`

### ISSUE THREAD

**Issue by ZhymabekRoman** [omegaui/cliptopia#22]
Thanks for the project!

OS: Arch Linux

![image](https://github.com/omegaui/cliptopia/assets/61125068/0f15c2e2-57eb-4bfa-ad48-948d6ebbb4c7)

```bash
 ./Cliptopia-1.0.0+2-x86_64.AppImage
Gtk-Message: 12:44:22.561: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:44:22.563: Failed to load module "canberra-gtk-module"

(cliptopia:4290): Gdk-CRITICAL **: 12:44:22.675: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: EmptyCause.noInitialElements

** (cliptopia:4290): WARNING **: 12:44:47.903: atk-bridge: get_device_events_reply: unknown signature
flutter: Null check operator used on a null value
flutter: #0      TooltipState._tooltipMessage (package:flutter/src/material/tooltip.dart:407)
flutter: #1      TooltipState.build (package:flutter/src/material/tooltip.dart:789)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
flutter: #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #13     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
flutter: #14     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #22     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
flutter: #23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #84     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #93     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
flutter: #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
```

**Comment by ZhymabekRoman** [comment]
Second problem: nothing happens when I press either "Bug Report" or "Here".

**Comment by omegaui** [comment]
![image](https://github.com/omegaui/cliptopia/assets/73544069/3de1805a-3cd0-46ce-be67-26efc4040eb7)


Loads fine on ubuntu.
Can you please check if you are able to replicate the issue by running from source.

**Comment by ZhymabekRoman** [comment]
Debug build from source code:
![image](https://github.com/omegaui/cliptopia/assets/61125068/adee31f2-9072-4acc-add9-cc6e1af580f2)

**Comment by omegaui** [comment]
Thank you for checking.
I've myself cross checked the sources for any such errors but I couldn't find one, may be the error is arising on arch only, this is strange actually.
I'll launch a vm and test myself.

**Comment by omegaui** [comment]
@ZhymabekRoman 
Can you please tell me the flutter version you are using?

**Comment by ZhymabekRoman** [comment]
```bash
$  flutter --version
Flutter 3.16.3 • channel stable • git@github.com:flutter/flutter.git
Framework • revision b0366e0a3f (4 weeks ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```
