### ISSUE TITLE
# Bug Report N-766

### ISSUE THREAD

**Issue by thenriques45** [omegaui/cliptopia#7]
**Distro**: "Fedora Linux 39 (Workstation Edition)"
**Version**: 39
**Parent Distro**: no-parent-distro

**Time**: Dec 13, 2023 14:55
**Area of Impact**: PROD Session
**Message**: [Zone Guard]
**Additional Description**: Error caught by Zone Guard.
**Error**: ProcessException: Arquivo ou diretório inexistente
  Command: java --help
```shell
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      doesCommandExists (package:cliptopia/core/utils.dart:354)
#5      _SettingsInitializedStateViewState._buildTroubleshootPage.buildTile (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:616)
#6      _SettingsInitializedStateViewState._buildTroubleshootPage (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:728)
#7      _SettingsInitializedStateViewState.build (package:cliptopia/app/settings/presentation/states/settings_initialized_state_view.dart:157)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#52     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#54     Element.updateChildren (package:flutter/src/widgets/framework.dart:4024)
#55     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#60     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#64     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#65     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#69     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#71     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#72     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#89     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#93     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#101    StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#110    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#129    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#146    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#148    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#152    StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#155    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#157    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#163    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#164    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#169    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#171    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#179    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#182    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#184    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#188    StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#192    StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#194    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#198    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#202    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#205    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#207    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#210    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#212    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#215    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#217    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#218    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#219    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#220    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#221    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#222    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#223    _rootRun (dart:async/zone.dart:1399)
#224    _CustomZone.run (dart:async/zone.dart:1301)
#225    _CustomZone.runGuarded (dart:async/zone.dart:1209)
#226    _invoke (dart:ui/hooks.dart:314)
#227    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#228    _drawFrame (dart:ui/hooks.dart:283)
```

**Comment by omegaui** [comment]
@thenriques45 

Seems like java is not installed or is not on path.

**Comment by omegaui** [comment]
Hi!

You require java 17 or above on path to paste from Cliptopia.

**Comment by omegaui** [comment]
Let me know if it works, so that I can close this issue.

**Comment by omegaui** [comment]
You may reopen this issue, if installing java doesn't solves it.
